function sendDataSet(this, varargin)

% === Inputs ==============================================================

p = inputParser;
addRequired(p, 'index', @isnumeric);
addParameter(p, 'sendData', true, @islogical);
parse(p, varargin{:});
   
index = p.Results.index; 
sendData = p.Results.sendData; 


% =========================================================================

% --- Preparation
transform = 'none';
i = ['set:' num2str(index) ':'];

% --- Expedition
this.sendCommand([i 'new;'...
    i 'type:XYZ;' ...
    i 'name:' this.dataSet(index).name ';' ...
    i 'X:' num2str(this.dataSet(index).X) ';' ...
    i 'Y:' num2str(this.dataSet(index).Y) ';' ...
    i 'Z:' num2str(this.dataSet(index).Z) ';' ...
    i 'T:' num2str(this.dataSet(index).T) ';' ...
    i 't:' num2str(this.dataSet(index).t) ';' ...
    i 'transform:' transform ';' ...
    i 'visible:' num2str(this.dataSet(index).visible) ';' ...
    i 'frozen:' num2str(this.dataSet(index).frozen) ';' ...
    i 'x2um:' num2str(this.dataSet(index).x2um) ';' ...
    i 'y2um:' num2str(this.dataSet(index).y2um) ';' ...
    i 'z2um:' num2str(this.dataSet(index).z2um) ';' ...
    i 't2s:' num2str(this.dataSet(index).t2s)]);

% --- Send initial data
if sendData
    this.sendData(index, 'image', 'z', 1, 't', 1);
end